name: HiTimTurner
favicon: null
layout_spectrum: 0.95852
typography_spectrum: 0.17967
title: >-
  Personal Blog for my Fitness, Nutrition, Proffesional Development and any
  books im reading
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1875
  lightness: 0.13095781859010458
  saturation: 0.0994036034680903
  rhythmicContrast: 0.25
purpose: []
